import { gUuidV4 } from '../utils/string';

export const MOCK_VEHICLE_DATA = [
  { id: gUuidV4(), value: 'AC', name: 'AC' },
  { id: gUuidV4(), value: 'ALPINA', name: 'ALPINA' },
  { id: gUuidV4(), value: 'Abarth', name: 'Abarth' },
  { id: gUuidV4(), value: 'Acura', name: 'Acura' },
  { id: gUuidV4(), value: 'Aixam', name: 'Aixam' },
  { id: gUuidV4(), value: 'Alfa Romeo', name: 'Alfa Romeo' },
  { id: gUuidV4(), value: 'Artega', name: 'Artega' },
  { id: gUuidV4(), value: 'Asia Motors', name: 'Asia Motors' },
  { id: gUuidV4(), value: 'Aston Martin', name: 'Aston Martin' },
  { id: gUuidV4(), value: 'Audi', name: 'Audi' },
  { id: gUuidV4(), value: 'Austin', name: 'Austin' },
  { id: gUuidV4(), value: 'Austin Healey', name: 'Austin Healey' },
  { id: gUuidV4(), value: 'BMW', name: 'BMW' },
  { id: gUuidV4(), value: 'Bentley', name: 'Bentley' },
  { id: gUuidV4(), value: 'Borgward', name: 'Borgward' },
  { id: gUuidV4(), value: 'Brilliance', name: 'Brilliance' },
  { id: gUuidV4(), value: 'Bugatti', name: 'Bugatti' },
  { id: gUuidV4(), value: 'Buick', name: 'Buick' },
  { id: gUuidV4(), value: 'Cadillac', name: 'Cadillac' },
  { id: gUuidV4(), value: 'Casalini', name: 'Casalini' },
  { id: gUuidV4(), value: 'Caterham', name: 'Caterham' },
  { id: gUuidV4(), value: 'Chatenet', name: 'Chatenet' },
  { id: gUuidV4(), value: 'Chevrolet', name: 'Chevrolet' },
  { id: gUuidV4(), value: 'Chrysler', name: 'Chrysler' },
  { id: gUuidV4(), value: 'Citroën', name: 'Citroën' },
  { id: gUuidV4(), value: 'Cobra', name: 'Cobra' },
  { id: gUuidV4(), value: 'Corvette', name: 'Corvette' },
  { id: gUuidV4(), value: 'DS Automobiles', name: 'DS Automobiles' },
  { id: gUuidV4(), value: 'Dacia', name: 'Dacia' },
  { id: gUuidV4(), value: 'Daewoo', name: 'Daewoo' },
  { id: gUuidV4(), value: 'Daihatsu', name: 'Daihatsu' },
  { id: gUuidV4(), value: 'DeTomaso', name: 'DeTomaso' },
  { id: gUuidV4(), value: 'Dodge', name: 'Dodge' },
  { id: gUuidV4(), value: 'Donkervoort', name: 'Donkervoort' },
  { id: gUuidV4(), value: 'Ferrari', name: 'Ferrari' },
  { id: gUuidV4(), value: 'Fiat', name: 'Fiat' },
  { id: gUuidV4(), value: 'Fisker', name: 'Fisker' },
  { id: gUuidV4(), value: 'Ford', name: 'Ford' },
  { id: gUuidV4(), value: 'GAC Gonow', name: 'GAC Gonow' },
  { id: gUuidV4(), value: 'GMC', name: 'GMC' },
  { id: gUuidV4(), value: 'Gemballa', name: 'Gemballa' },
  { id: gUuidV4(), value: 'Grecav', name: 'Grecav' },
  { id: gUuidV4(), value: 'Hamann', name: 'Hamann' },
  { id: gUuidV4(), value: 'Holden', name: 'Holden' },
  { id: gUuidV4(), value: 'Honda', name: 'Honda' },
  { id: gUuidV4(), value: 'Hummer', name: 'Hummer' },
  { id: gUuidV4(), value: 'Hyundai', name: 'Hyundai' },
  { id: gUuidV4(), value: 'Infiniti', name: 'Infiniti' },
  { id: gUuidV4(), value: 'Isuzu', name: 'Isuzu' },
  { id: gUuidV4(), value: 'Iveco', name: 'Iveco' },
  { id: gUuidV4(), value: 'Jaguar', name: 'Jaguar' },
  { id: gUuidV4(), value: 'Jeep', name: 'Jeep' },
  { id: gUuidV4(), value: 'KTM', name: 'KTM' },
  { id: gUuidV4(), value: 'Kia', name: 'Kia' },
  { id: gUuidV4(), value: 'Koenigsegg', name: 'Koenigsegg' },
  { id: gUuidV4(), value: 'Lada', name: 'Lada' },
  { id: gUuidV4(), value: 'Lamborghini', name: 'Lamborghini' },
  { id: gUuidV4(), value: 'Lancia', name: 'Lancia' },
  { id: gUuidV4(), value: 'Land Rover', name: 'Land Rover' },
  { id: gUuidV4(), value: 'Landwind', name: 'Landwind' },
  { id: gUuidV4(), value: 'Lexus', name: 'Lexus' },
  { id: gUuidV4(), value: 'Ligier', name: 'Ligier' },
  { id: gUuidV4(), value: 'Lincoln', name: 'Lincoln' },
  { id: gUuidV4(), value: 'Lotus', name: 'Lotus' },
  { id: gUuidV4(), value: 'MG', name: 'MG' },
  { id: gUuidV4(), value: 'MINI', name: 'MINI' },
  { id: gUuidV4(), value: 'Mahindra', name: 'Mahindra' },
  { id: gUuidV4(), value: 'Maserati', name: 'Maserati' },
  { id: gUuidV4(), value: 'Maybach', name: 'Maybach' },
  { id: gUuidV4(), value: 'Mazda', name: 'Mazda' },
  { id: gUuidV4(), value: 'McLaren', name: 'McLaren' },
  { id: gUuidV4(), value: 'Mercedes-Benz', name: 'Mercedes-Benz' },
  { id: gUuidV4(), value: 'Microcar', name: 'Microcar' },
  { id: gUuidV4(), value: 'Mitsubishi', name: 'Mitsubishi' },
  { id: gUuidV4(), value: 'Morgan', name: 'Morgan' },
  { id: gUuidV4(), value: 'NSU', name: 'NSU' },
  { id: gUuidV4(), value: 'Nissan', name: 'Nissan' },
  { id: gUuidV4(), value: 'Oldsmobile', name: 'Oldsmobile' },
  { id: gUuidV4(), value: 'Opel', name: 'Opel' },
  { id: gUuidV4(), value: 'Other', name: 'Other' },
  { id: gUuidV4(), value: 'Pagani', name: 'Pagani' },
  { id: gUuidV4(), value: 'Peugeot', name: 'Peugeot' },
  { id: gUuidV4(), value: 'Piaggio', name: 'Piaggio' },
  { id: gUuidV4(), value: 'Plymouth', name: 'Plymouth' },
  { id: gUuidV4(), value: 'Pontiac', name: 'Pontiac' },
  { id: gUuidV4(), value: 'Porsche', name: 'Porsche' },
  { id: gUuidV4(), value: 'Proton', name: 'Proton' },
  { id: gUuidV4(), value: 'Renault', name: 'Renault' },
  { id: gUuidV4(), value: 'Rolls-Royce', name: 'Rolls-Royce' },
  { id: gUuidV4(), value: 'Rover', name: 'Rover' },
  { id: gUuidV4(), value: 'Ruf', name: 'Ruf' },
  { id: gUuidV4(), value: 'Saab', name: 'Saab' },
  { id: gUuidV4(), value: 'Santana', name: 'Santana' },
  { id: gUuidV4(), value: 'Seat', name: 'Seat' },
  { id: gUuidV4(), value: 'Skoda', name: 'Skoda' },
  { id: gUuidV4(), value: 'Smart', name: 'Smart' },
  { id: gUuidV4(), value: 'Spyker', name: 'Spyker' },
  { id: gUuidV4(), value: 'Ssangyong', name: 'Ssangyong' },
  { id: gUuidV4(), value: 'Subaru', name: 'Subaru' },
  { id: gUuidV4(), value: 'Suzuki', name: 'Suzuki' },
  { id: gUuidV4(), value: 'TECHART', name: 'TECHART' },
  { id: gUuidV4(), value: 'TVR', name: 'TVR' },
  { id: gUuidV4(), value: 'Talbot', name: 'Talbot' },
  { id: gUuidV4(), value: 'Tata', name: 'Tata' },
  { id: gUuidV4(), value: 'Tesla', name: 'Tesla' },
  { id: gUuidV4(), value: 'Toyota', name: 'Toyota' },
  { id: gUuidV4(), value: 'Trabant', name: 'Trabant' },
  { id: gUuidV4(), value: 'Triumph', name: 'Triumph' },
  { id: gUuidV4(), value: 'Volkswagen', name: 'Volkswagen' },
  { id: gUuidV4(), value: 'Volvo', name: 'Volvo' },
  { id: gUuidV4(), value: 'Wartburg', name: 'Wartburg' },
  { id: gUuidV4(), value: 'Westfield', name: 'Westfield' },
  { id: gUuidV4(), value: 'Wiesmann', name: 'Wiesmann' },
  { id: gUuidV4(), value: 'speedART', name: 'speedART' },
];

export const MOCK_CAR_MENU_DATA = [
  'Cabriolet/Roaster',
  'Estate Car',
  'Off-road Vehicle/Pickup Truck',
  'Saloon',
  'Small Car',
  'Sport Car/Coupe',
  'Van/Minibus',
  'Other',
];
export const MOTOR_BIKES_MENU_DATA = [
  'Chopper/Cruiser',
  'Combination/Sidecar',
  'Dirt Bike',
  'Enduro/Touring Enduro',
  'Lightweight Motorcycle/Motorbike',
  'Motor-assisted Bicycle/Small Moped',
  'Motorcycle',
  'Naked Bike',
  'Racing',
  'Rally/Cross',
  'Pocketbike',
  'Quad',
  'Sport Touring Motorcycles',
  'Streetfighter',
  'Scooter',
  'Sports/Super Sports Bike',
  'Trike',
  'Other',
  'Super Moto',
  'Tour',
];
export const MOCK_MOTOR_HOMES_MENU_DATA = [
  'Alcoves',
  'Cabin',
  'Caravan',
  'Intergrated',
  'Mobile Home',
  'Motor Homes, Other',
  'Motor Homes/Pickup Trucks',
  'Partly Integrated',
  'Van',
  'Other',
];
export const MOCK_TRUCKS_MENU_DATA = [
  'Vans/Trucks up to 7.5t',
  'Trucks over 7.5',
  'Semi-trailers truck',
  'Trailers',
  'Semi-trailers',
  'Construction Machines',
  'Buses',
  'Agricultural Vehicles',
  'Forklift Trucks',
];
export const MOCK_OTHERS_DATA = [
  'Parts and accessories',
  'Equipment for engineers',
  'Vintage cars',
  'Cleaning and maintenance',
  'Tires and Wheels',
  'Part for commercial vehicles',
  'Vintage Motorcycles',
  'Search Vehicles',
  'Spare car parts',
  'Spare parts for engineer',
  'Parts and accessories for classic c',
  'Car Accessories',
  'Oldtimers',
  'Other classic cars',
];

export const MOCK_LOGGED_IN = true;
