export const MakeData = [
  { value: 'AC', name: 'AC' },
  { value: 'ALPINA', name: 'ALPINA' },
  { value: 'Abarth', name: 'Abarth' },
  { value: 'Acura', name: 'Acura' },
  { value: 'Aixam', name: 'Aixam' },
  { value: 'Alfa Romeo', name: 'Alfa Romeo' },
  { value: 'Artega', name: 'Artega' },
  { value: 'Asia Motors', name: 'Asia Motors' },
  { value: 'Aston Martin', name: 'Aston Martin' },
  { value: 'Audi', name: 'Audi' },
  { value: 'Austin', name: 'Austin' },
  { value: 'Austin Healey', name: 'Austin Healey' },
  { value: 'BMW', name: 'BMW' },
  { value: 'Bentley', name: 'Bentley' },
  { value: 'Borgward', name: 'Borgward' },
  { value: 'Brilliance', name: 'Brilliance' },
  { value: 'Bugatti', name: 'Bugatti' },
  { value: 'Buick', name: 'Buick' },
  { value: 'Cadillac', name: 'Cadillac' },
  { value: 'Casalini', name: 'Casalini' },
  { value: 'Caterham', name: 'Caterham' },
  { value: 'Chatenet', name: 'Chatenet' },
  { value: 'Chevrolet', name: 'Chevrolet' },
  { value: 'Chrysler', name: 'Chrysler' },
  { value: 'Citroën', name: 'Citroën' },
  { value: 'Cobra', name: 'Cobra' },
  { value: 'Corvette', name: 'Corvette' },
  { value: 'DS Automobiles', name: 'DS Automobiles' },
  { value: 'Dacia', name: 'Dacia' },
  { value: 'Daewoo', name: 'Daewoo' },
  { value: 'Daihatsu', name: 'Daihatsu' },
  { value: 'DeTomaso', name: 'DeTomaso' },
  { value: 'Dodge', name: 'Dodge' },
  { value: 'Donkervoort', name: 'Donkervoort' },
  { value: 'Ferrari', name: 'Ferrari' },
  { value: 'Fiat', name: 'Fiat' },
  { value: 'Fisker', name: 'Fisker' },
  { value: 'Ford', name: 'Ford' },
  { value: 'GAC Gonow', name: 'GAC Gonow' },
  { value: 'GMC', name: 'GMC' },
  { value: 'Gemballa', name: 'Gemballa' },
  { value: 'Grecav', name: 'Grecav' },
  { value: 'Hamann', name: 'Hamann' },
  { value: 'Holden', name: 'Holden' },
  { value: 'Honda', name: 'Honda' },
  { value: 'Hummer', name: 'Hummer' },
  { value: 'Hyundai', name: 'Hyundai' },
  { value: 'Infiniti', name: 'Infiniti' },
  { value: 'Isuzu', name: 'Isuzu' },
  { value: 'Iveco', name: 'Iveco' },
  { value: 'Jaguar', name: 'Jaguar' },
  { value: 'Jeep', name: 'Jeep' },
  { value: 'KTM', name: 'KTM' },
  { value: 'Kia', name: 'Kia' },
  { value: 'Koenigsegg', name: 'Koenigsegg' },
  { value: 'Lada', name: 'Lada' },
  { value: 'Lamborghini', name: 'Lamborghini' },
  { value: 'Lancia', name: 'Lancia' },
  { value: 'Land Rover', name: 'Land Rover' },
  { value: 'Landwind', name: 'Landwind' },
  { value: 'Lexus', name: 'Lexus' },
  { value: 'Ligier', name: 'Ligier' },
  { value: 'Lincoln', name: 'Lincoln' },
  { value: 'Lotus', name: 'Lotus' },
  { value: 'MG', name: 'MG' },
  { value: 'MINI', name: 'MINI' },
  { value: 'Mahindra', name: 'Mahindra' },
  { value: 'Maserati', name: 'Maserati' },
  { value: 'Maybach', name: 'Maybach' },
  { value: 'Mazda', name: 'Mazda' },
  { value: 'McLaren', name: 'McLaren' },
  { value: 'Mercedes-Benz', name: 'Mercedes-Benz' },
  { value: 'Microcar', name: 'Microcar' },
  { value: 'Mitsubishi', name: 'Mitsubishi' },
  { value: 'Morgan', name: 'Morgan' },
  { value: 'NSU', name: 'NSU' },
  { value: 'Nissan', name: 'Nissan' },
  { value: 'Oldsmobile', name: 'Oldsmobile' },
  { value: 'Opel', name: 'Opel' },
  { value: 'Other', name: 'Other' },
  { value: 'Pagani', name: 'Pagani' },
  { value: 'Peugeot', name: 'Peugeot' },
  { value: 'Piaggio', name: 'Piaggio' },
  { value: 'Plymouth', name: 'Plymouth' },
  { value: 'Pontiac', name: 'Pontiac' },
  { value: 'Porsche', name: 'Porsche' },
  { value: 'Proton', name: 'Proton' },
  { value: 'Renault', name: 'Renault' },
  { value: 'Rolls-Royce', name: 'Rolls-Royce' },
  { value: 'Rover', name: 'Rover' },
  { value: 'Ruf', name: 'Ruf' },
  { value: 'Saab', name: 'Saab' },
  { value: 'Santana', name: 'Santana' },
  { value: 'Seat', name: 'Seat' },
  { value: 'Skoda', name: 'Skoda' },
  { value: 'Smart', name: 'Smart' },
  { value: 'Spyker', name: 'Spyker' },
  { value: 'Ssangyong', name: 'Ssangyong' },
  { value: 'Subaru', name: 'Subaru' },
  { value: 'Suzuki', name: 'Suzuki' },
  { value: 'TECHART', name: 'TECHART' },
  { value: 'TVR', name: 'TVR' },
  { value: 'Talbot', name: 'Talbot' },
  { value: 'Tata', name: 'Tata' },
  { value: 'Tesla', name: 'Tesla' },
  { value: 'Toyota', name: 'Toyota' },
  { value: 'Trabant', name: 'Trabant' },
  { value: 'Triumph', name: 'Triumph' },
  { value: 'Volkswagen', name: 'Volkswagen' },
  { value: 'Volvo', name: 'Volvo' },
  { value: 'Wartburg', name: 'Wartburg' },
  { value: 'Westfield', name: 'Westfield' },
  { value: 'Wiesmann', name: 'Wiesmann' },
  { value: 'speedART', name: 'speedART' },
];

export const CarMenuData = [
  'Cabriolet/Roaster',
  'Estate Car',
  'Off-road Vehicle/Pickup Truck',
  'Saloon',
  'Small Car',
  'Sport Car/Coupe',
  'Van/Minibus',
  'Other',
];
export const MotorbikesMenuData = [
  'Chopper/Cruiser',
  'Combination/Sidecar',
  'Dirt Bike',
  'Enduro/Touring Enduro',
  'Lightweight Motorcycle/Motorbike',
  'Motor-assisted Bicycle/Small Moped',
  'Motorcycle',
  'Naked Bike',
  'Racing',
  'Rally/Cross',
  'Pocketbike',
  'Quad',
  'Sport Touring Motorcycles',
  'Streetfighter',
  'Scooter',
  'Sports/Super Sports Bike',
  'Trike',
  'Other',
  'Super Moto',
  'Tour',
];
export const MotorhomesMenuData = [
  'Alcoves',
  'Cabin',
  'Caravan',
  'Intergrated',
  'Mobile Home',
  'Motor Homes, Other',
  'Motor Homes/Pickup Trucks',
  'Partly Integrated',
  'Van',
  'Other',
];
export const TrucksMenuData = [
  'Vans/Trucks up to 7.5t',
  'Trucks over 7.5',
  'Semi-trailers truck',
  'Trailers',
  'Semi-trailers',
  'Construction Machines',
  'Buses',
  'Agricultural Vehicles',
  'Forklift Trucks',
];
export const OthersData = [
  'Parts and accessories',
  'Equipment for engineers',
  'Vintage cars',
  'Cleaning and maintenance',
  'Tires and Wheels',
  'Part for commercial vehicles',
  'Vintage Motorcycles',
  'Search Vehicles',
  'Spare car parts',
  'Spare parts for engineer',
  'Parts and accessories for classic c',
  'Car Accessories',
  'Oldtimers',
  'Other classic cars',
];
